workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
      when: never
    - when: always

stages:
  - deploy


deploy:
  before_script:
    - docker login -u ${dockerhub_id} -p ${dockerhub_password}

  stage: deploy

  image: docker

  services:
    - name: docker:dind

  script:
    - docker build -t jhkimdocker/busapi:${VERSION} .

    - docker push jhkimdocker/busapi:${VERSION}

